spring:
  application:
    name: File-Storage-Service
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://postgres:5432/CaseLab
    username: GreenAtom
    password: 3rjwi624eofi634eio6w34fj2oi9ji6g5o7w3g5j7iwwji567pqg
    driver-class-name: org.postgresql.Driver
logging:
  level:
    web: debug
server:
  port: 8080
